table game_genres
	lineageTag: 3a32420b-76aa-4485-9134-2d8daeabc32a

	column AppID
		dataType: int64
		formatString: 0
		lineageTag: 70f75e2f-ab57-477c-8883-327f1e5f2641
		summarizeBy: none
		sourceColumn: AppID

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 2e15d5bc-a538-48d6-9f41-7cede81bff2e
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column 'Release date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: fc28fc9e-8d1b-4469-85da-1c26e26f2d1a
		summarizeBy: none
		sourceColumn: Release date

		variation Variation
			isDefault
			relationship: 04c14ad8-cd24-4cd9-a491-82594a654288
			defaultHierarchy: LocalDateTable_cc4ad0ee-5b2a-4495-ab70-41cf77c8f1f5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Estimated owners'
		dataType: string
		lineageTag: 96170cc6-b59a-42e2-9a5a-7532231d9be4
		summarizeBy: none
		sourceColumn: Estimated owners

		annotation SummarizationSetBy = Automatic

	column 'Peak CCU'
		dataType: int64
		formatString: 0
		lineageTag: 944cd76a-27a5-4bdc-bb2e-745e6168c612
		summarizeBy: sum
		sourceColumn: Peak CCU

		annotation SummarizationSetBy = Automatic

	column 'Required age'
		dataType: int64
		formatString: 0
		lineageTag: bd105de5-9c6a-42be-bd79-7a93618382ca
		summarizeBy: sum
		sourceColumn: Required age

		annotation SummarizationSetBy = Automatic

	column Price
		dataType: double
		lineageTag: 8241e853-f246-4c7e-8f32-52ba14f1c027
		summarizeBy: sum
		sourceColumn: Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Discount
		dataType: int64
		formatString: 0
		lineageTag: 89397349-8e30-4bb7-a236-098ddf8d9e24
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column 'DLC count'
		dataType: int64
		formatString: 0
		lineageTag: 5d5e2549-c06d-4192-b907-809f28170416
		summarizeBy: sum
		sourceColumn: DLC count

		annotation SummarizationSetBy = Automatic

	column Windows
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6de0eae8-9cdf-4311-8a04-7d60587108af
		summarizeBy: none
		sourceColumn: Windows

		annotation SummarizationSetBy = Automatic

	column Mac
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: fefcad2e-1ca3-4648-a29a-a176391ea71c
		summarizeBy: none
		sourceColumn: Mac

		annotation SummarizationSetBy = Automatic

	column Linux
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 76bedb2a-e536-4693-beee-97a88130ef18
		summarizeBy: none
		sourceColumn: Linux

		annotation SummarizationSetBy = Automatic

	column 'Metacritic score'
		dataType: int64
		formatString: 0
		lineageTag: a3ad0a6e-6cf7-47c7-ba09-7e2920b4af0a
		summarizeBy: sum
		sourceColumn: Metacritic score

		annotation SummarizationSetBy = Automatic

	column 'User score'
		dataType: int64
		formatString: 0
		lineageTag: d37aa619-d1c0-41cd-977a-d08923bac77c
		summarizeBy: sum
		sourceColumn: User score

		annotation SummarizationSetBy = Automatic

	column Positive
		dataType: int64
		formatString: 0
		lineageTag: 1b07a85b-817f-4189-bc5c-2a2c5291a3cd
		summarizeBy: sum
		sourceColumn: Positive

		annotation SummarizationSetBy = Automatic

	column Negative
		dataType: int64
		formatString: 0
		lineageTag: eabc63c8-3d7c-4293-8e6c-bfaf280bb287
		summarizeBy: sum
		sourceColumn: Negative

		annotation SummarizationSetBy = Automatic

	column 'Score rank'
		dataType: string
		lineageTag: ee1f5ff6-f468-40f5-b33a-444740c05539
		summarizeBy: none
		sourceColumn: Score rank

		annotation SummarizationSetBy = Automatic

	column Achievements
		dataType: int64
		formatString: 0
		lineageTag: cd50a8d0-8f99-4b05-b472-3e2bac230dee
		summarizeBy: sum
		sourceColumn: Achievements

		annotation SummarizationSetBy = Automatic

	column Recommendations
		dataType: int64
		formatString: 0
		lineageTag: f9328bf2-b886-490a-ae4a-f6630f936093
		summarizeBy: sum
		sourceColumn: Recommendations

		annotation SummarizationSetBy = Automatic

	column 'Average playtime forever'
		dataType: int64
		formatString: 0
		lineageTag: 2dbb6032-de4a-457c-899f-a121739b5cdd
		summarizeBy: sum
		sourceColumn: Average playtime forever

		annotation SummarizationSetBy = Automatic

	column 'Average playtime two weeks'
		dataType: int64
		formatString: 0
		lineageTag: 05fb3aca-3dd0-464f-b1a3-f8e1923b1712
		summarizeBy: sum
		sourceColumn: Average playtime two weeks

		annotation SummarizationSetBy = Automatic

	column 'Median playtime forever'
		dataType: int64
		formatString: 0
		lineageTag: 8011563f-284b-4043-bcf6-5418aae8cdf3
		summarizeBy: sum
		sourceColumn: Median playtime forever

		annotation SummarizationSetBy = Automatic

	column 'Median playtime two weeks'
		dataType: int64
		formatString: 0
		lineageTag: 1878e3d4-bfde-4c7f-ab98-e610d285f1ad
		summarizeBy: sum
		sourceColumn: Median playtime two weeks

		annotation SummarizationSetBy = Automatic

	column Developers
		dataType: string
		lineageTag: 6dec2525-bcf5-47b5-ba9c-ae2a9e1d3709
		summarizeBy: none
		sourceColumn: Developers

		annotation SummarizationSetBy = Automatic

	column Publishers
		dataType: string
		lineageTag: e9e7ca38-130c-4390-9a14-34b7cf49b1c3
		summarizeBy: none
		sourceColumn: Publishers

		annotation SummarizationSetBy = Automatic

	column Categories
		dataType: string
		lineageTag: 1e9b0b0e-f595-4bdf-bd39-d9299aee280c
		summarizeBy: none
		sourceColumn: Categories

		annotation SummarizationSetBy = Automatic

	column Genres
		dataType: string
		lineageTag: 262fcc93-0fe8-4f07-b7fb-773089c81356
		summarizeBy: none
		sourceColumn: Genres

		annotation SummarizationSetBy = Automatic

	column Tags
		dataType: string
		lineageTag: 0b3add1f-9fcf-4a55-b457-e6fdc971f91f
		summarizeBy: none
		sourceColumn: Tags

		annotation SummarizationSetBy = Automatic

	partition game_genres = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("D:\Data Analyst Stuff\Python\steam_games_perfected.csv"), [Delimiter = ",", Columns = 28, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"AppID", Int64.Type}, {"Name", type text}, {"Release date", type date}, {"Estimated owners", type text}, {"Peak CCU", Int64.Type}, {"Required age", Int64.Type}, {"Price", type number}, {"Discount", Int64.Type}, {"DLC count", Int64.Type}, {"Windows", type logical}, {"Mac", type logical}, {"Linux", type logical}, {"Metacritic score", Int64.Type}, {"User score", Int64.Type}, {"Positive", Int64.Type}, {"Negative", Int64.Type}, {"Score rank", type text}, {"Achievements", Int64.Type}, {"Recommendations", Int64.Type}, {"Average playtime forever", Int64.Type}, {"Average playtime two weeks", Int64.Type}, {"Median playtime forever", Int64.Type}, {"Median playtime two weeks", Int64.Type}, {"Developers", type text}, {"Publishers", type text}, {"Categories", type text}, {"Genres", type text}, {"Tags", type text}}, "en-US"),
				    #"Split Column by Delimiter" = Table.ExpandListColumn(Table.TransformColumns(#"Changed column type", {{"Genres", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "Genres"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Genres", type text}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Changed Type",{{"Genres", Text.Trim, type text}})
				in
				  #"Trimmed Text"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

